development:
  adapter: postgresql
  encoding: unicode
  database: baseball_stats
  pool: 5
  usernamename: username
  password:
  host: localhost
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: baseball_stats_test
  pool: 5
  usernamename: username
  password:
  host: localhost
  timeout: 5000
